---
title: "a2_task3_kat_leigh"
author: "Kat Leigh"
date: "2/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(lubridate)
library(ggplot2)
library(jtools)
library(ggfortify)
library(broom)
library(patchwork)
library(scales)
library(splitstackshape)
library(stringi)

```

Tidy Tuesday Plastics

```{r}
# read in data

plastics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-26/plastics.csv') %>% 
  clean_names() %>% distinct()

plastics <- plastics %>%
  mutate(parent_company = tolower(parent_company),
         country = tolower(country)) %>% 
  mutate(parent_company = stri_trans_general(parent_company, id = "latin-ascii"),
         country = stri_trans_general(country, id = "latin-ascii")) %>%
  mutate(parent_company = case_when(str_detect(parent_company, c('#error!', 'error!', 'null')) ~ 'unbranded',
                          str_detect(parent_company, c('zott (germany)', 'zost')) ~ 'zott',
                          str_detect(parent_company, c('zydus wellness')) ~ 'zydus',
                          str_detect(parent_company, c('colgate-palmolive', 'colgate palmolive')) ~ 'colgate',
                          str_detect(parent_company, c('zydus wellness')) ~ 'zydus',
                          str_detect(parent_company, c('^foods ltd')) ~ 'a & p foods ltd',
                          str_detect(parent_company, c('^a mild', 'a mild^')) ~ 'a mild',
                          str_detect(parent_company, c('a1 chips^')) ~ 'a1',
                          str_detect(parent_company, c('abc kecap^')) ~ 'abc kecap',
                          str_detect(parent_company, c('kopi susu^')) ~ 'kopi susu',
                          str_detect(parent_company, c('absolute^')) ~ 'absolute manufacturing',
str_detect(parent_company, c('acecook^', 'acebook^')) ~ 'ace cook',
str_detect(parent_company, c('agua de las^')) ~ 'agua de las misiones',
                          TRUE ~ parent_company)) %>% 
  filter(parent_company != "grand total") %>%
  mutate(parent_company = as.factor(parent_company),
         country = as.factor(country)) %>% ungroup() %>% drop_na()

plastics <- plastics %>% 
  group_by(country, parent_company) %>% 
  summarise(grand_total = sum(grand_total)/sum(num_events),
         hdpe = sum(hdpe)/sum(num_events),
         ldpe = sum(ldpe)/sum(num_events),
         o = sum(o)/sum(num_events),
         pet = sum(pet)/sum(num_events),
         pp = sum(pp)/sum(num_events),
         ps = sum(ps)/sum(num_events),
         pvc = sum(pvc)/sum(num_events)) %>% 
  distinct()

prop_per_ev_plastics <- plastics %>% 
  mutate(hdpe = hdpe/grand_total,
         ldpe = ldpe/grand_total,
         o = o/grand_total,
         pet = pet/grand_total,
         pp = pp/grand_total,
         ps = ps/grand_total,
         pvc = pvc/grand_total)

#find top companies

top_comp <- prop_per_ev_plastics %>%
  group_by(parent_company) %>% 
  summarize(totalz = sum(grand_total)) %>% ungroup() %>% 
  arrange(-totalz) %>% head(20)

plastics_top_comp <- prop_per_ev_plastics %>%
  filter(parent_company %in% top_comp$parent_company)
  
plastics_top_comp_gath <- plastics_top_comp %>%
  group_by(parent_company, country) %>% 
  pivot_longer(cols = c(hdpe:pvc), names_to = "Type", values_to = "Value")
```

```{r}

# lm to see if parent company can be predicted by a total, country, and type of plastic

lm_test_h <- lm(hdpe ~ parent_company + country, data = plastics_top_comp)

lm_tidy_hdpe <- broom::tidy(lm_test_h) %>% 
  mutate(maybe_significant = ifelse(p.value < 0.05, "YES", "NO")) %>% 
  mutate(Type = "hdpe")

lm_test_l <- lm(ldpe ~ parent_company + country, data = plastics_top_comp)

lm_tidy_ldpe <- broom::tidy(lm_test_l) %>% 
  mutate(maybe_significant = ifelse(p.value < 0.05, "YES", "NO")) %>% 
  mutate(Type = "ldpe")

lm_test_o <- lm(o ~ parent_company + country, data = plastics_top_comp)

lm_tidy_o <- broom::tidy(lm_test_o) %>% 
  mutate(maybe_significant = ifelse(p.value < 0.05, "YES", "NO")) %>% 
  mutate(Type = "o")

lm_test_pet <- lm(pet ~ parent_company + country, data = plastics_top_comp)

lm_tidy_pet <- broom::tidy(lm_test_pet) %>% 
  mutate(maybe_significant = ifelse(p.value < 0.05, "YES", "NO")) %>% 
  mutate(Type = "pet")

lm_test_pp <- lm(pp ~ parent_company + country, data = plastics_top_comp)

lm_tidy_pp <- broom::tidy(lm_test_pp) %>% 
  mutate(maybe_significant = ifelse(p.value < 0.05, "YES", "NO")) %>% 
  mutate(Type = "pp")

lm_test_ps <- lm(ps ~ parent_company + country, data = plastics_top_comp)

lm_tidy_ps <- broom::tidy(lm_test_ps) %>% 
  mutate(maybe_significant = ifelse(p.value < 0.05, "YES", "NO")) %>% 
  mutate(Type = "ps")

lm_test_pvc <- lm(pvc ~ parent_company + country, data = plastics_top_comp)

lm_tidy_pvc <- broom::tidy(lm_test_pvc) %>% 
  mutate(maybe_significant = ifelse(p.value < 0.05, "YES", "NO")) %>% 
  mutate(Type = "pvc")

# get r-squared values for each model

summary_tidy_hpde <- summary(lm_test_h)
r_sqrd_hpde <- round(summary_tidy_hpde$r.squared, 3)

summary_tidy_lpde <- summary(lm_test_l)
r_sqrd_lpde <- round(summary_tidy_lpde$r.squared, 3)

summary_tidy_o <- summary(lm_test_o)
r_sqrd_o <- round(summary_tidy_o$r.squared, 3)

summary_tidy_pet <- summary(lm_test_pet)
r_sqrd_pet <- round(summary_tidy_pet$r.squared, 3)

summary_tidy_pp <- summary(lm_test_pp)
r_sqrd_pp <- round(summary_tidy_pp$r.squared, 3)

summary_tidy_ps <- summary(lm_test_ps)
r_sqrd_ps <- round(summary_tidy_ps$r.squared, 3)

summary_tidy_pvc <- summary(lm_test_pvc)
r_sqrd_pvc <- round(summary_tidy_pvc$r.squared, 3)

# combine all the lm_tidy outputs

combo <- rbind(lm_tidy_hdpe, lm_tidy_ldpe, lm_tidy_o, lm_tidy_pet, lm_tidy_pp, lm_tidy_ps, lm_tidy_pvc)

# predict

predict_companies_hdpe <-  lm_test_h%>% 
  broom::augment(type.predict = "response") %>% 
  mutate(orig_val = hdpe) %>% 
  mutate(type = "hdpe") %>% 
  select(-hdpe)

predict_companies_ldpe <-  lm_test_l%>% 
  broom::augment(type.predict = "response") %>% 
  mutate(orig_val = ldpe) %>% 
  mutate(type = "ldpe") %>% 
  select(-ldpe)

predict_companies_o <-  lm_test_o%>% 
  broom::augment(type.predict = "response") %>% 
  mutate(orig_val = o) %>% 
  mutate(type = "o") %>% 
  select(-o)

predict_companies_pet <-  lm_test_pet%>% 
  broom::augment(type.predict = "response") %>% 
  mutate(orig_val = pet) %>% 
  mutate(type = "pet") %>% 
  select(-pet)

predict_companies_pp <-  lm_test_pp%>% 
  broom::augment(type.predict = "response") %>% 
  mutate(orig_val = pp) %>% 
  mutate(type = "pp") %>% 
  select(-pp)

predict_companies_ps <-  lm_test_ps%>% 
  broom::augment(type.predict = "response") %>% 
  mutate(orig_val = ps) %>% 
  mutate(type = "ps") %>% 
  select(-ps)

predict_companies_pvc <-  lm_test_pvc%>% 
  broom::augment(type.predict = "response") %>% 
  mutate(orig_val = pvc) %>% 
  mutate(type = "pvc") %>% 
  select(-pvc)

# combo plastic predictions

combo_pred <- rbind(predict_companies_hdpe, predict_companies_ldpe, predict_companies_o, predict_companies_pet, predict_companies_pp, predict_companies_ps, predict_companies_pvc) %>%   # mutate(orig_val= ifelse(orig_val == 1, .99999999, orig_val),
 #          .fitted = ifelse(.fitted == 1, .99999999, .fitted),
  #         orig_val= ifelse(orig_val == 0, .00000001, orig_val),
   #        .fitted = ifelse(.fitted == 1, .00000001, .fitted)) 
  drop_na() %>% 
  mutate(type = case_when(str_detect(type, 'hdpe') ~ 'hdpe R\u00B2: 0.316',
                          str_detect(type, 'ldpe') ~ 'ldpe R\u00B2: 0.443',
                          str_detect(type, 'o') ~ 'o R\u00B2: 0.546',
                          str_detect(type, 'pet') ~ 'pet R\u00B2: 0.648',
                          str_detect(type, 'pp') ~ 'pp R\u00B2: 0.448',
                          str_detect(type, 'ps')~ 'ps R\u00B2: 0.345',
                          str_detect(type, 'pvc') ~ 'pvc R\u00B2: 0.694'
                          ))

#combo_pred <- combo_pred %>%
#  pivot_longer(cols = c(orig_val, .fitted), values_to = "orig_fit")

```

```{r}
# vizualize

labz<- top_comp %>% 
  arrange(totalz)

ggplot()+
  geom_point(data = combo_pred, aes(x= orig_val, y= .fitted, color = type), alpha = .3, show.legend = FALSE)+
  geom_smooth(data = combo_pred, aes(x= orig_val, y= .fitted, color = type), na.rm = TRUE, method = 'lm')+
  #geom_line(data = combo_pred, aes(x= orig_val, y= .fitted, color = type), show.legend = FALSE)+
  theme_minimal()+
  labs(title= "Actual versus predicted proportion of total plastic counts per type of plastic",
       caption= str_wrap("A linear model was run to see how well knowledge of the country where the plastic was found and the company that produced it could predict the proportion of each type of plastic found during a single clean up event. Raw totals of each type of plastic per company, per country were divided by the number of events that took place in that country to get the average of each type per event. Then, each type was divided by the country-company per event grand total to obtain the proportion of each type found per event. The model is thus: lm([plastic type] ~ [parent company] + [country collected]). The actual proportion of each type of plastic is shown on the x axis, and the predicted proportion is shown on the y. The R-squared values for each type's linear model are shown as well.", 100),
       x= "Actual Proportion of Total",
       y= "Predicted Proportion of Total")
  



#ggplot(plastics_top_comp, aes(x = parent_company, y = grand_total_1))+
 # geom_point(aes(color = country), show.legend = FALSE)+
#  geom_smooth(aes(color = country), show.legend = FALSE)+
#  theme_minimal()


```
